version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: taskflow-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - common-network
      - backend

  postgres:
    image: postgres:16-alpine3.20
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - common-network
      - backend

volumes:
  postgres_data:

networks:
  common-network:
  backend:
